# Generated by Django 3.1.3 on 2020-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAnalysisAudiencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomAnalysisAudiencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('room_id', models.IntegerField(db_index=True, verbose_name='id room')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('meeting_code', models.IntegerField(db_index=True, verbose_name='id code in SILEG')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
